package eu.gillstrom.hsm.service;

import eu.gillstrom.hsm.testsupport.BankIdFixture;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Exercises the verification steps that had no test coverage: OCSP status,
 * OCSP response signature, responder issuer, nonce binding, and the scoping of
 * payload reads to the element the signature actually covers.
 *
 * <p>Extended in v1.4.0 with the responder-authority checks (a self-issued
 * responder certificate carrying a copied issuer DN; a responder without EKU
 * {@code id-kp-OCSPSigning}), the now-mandatory OCSP response, and the canonical
 * request binding carried in {@code usrNonVisibleData}.</p>
 *
 * <p>All material is generated by {@link BankIdFixture}. Nothing here is a
 * recorded production signature.</p>
 */
class BankIdSignatureVerificationTest {

    private BankIdFixture fx;
    private BankIdService service;

    @BeforeEach
    void setUp() throws Exception {
        fx = new BankIdFixture();
        service = new BankIdService(fx.anchors());
    }

    @Test
    @DisplayName("Valid signature, chain and OCSP response are accepted")
    void happyPath() throws Exception {
        String sig = fx.signedResponseBase64("Jag godkanner avtalet");
        BankIdService.BankIdResult r = service.verify(sig, fx.ocspResponseBase64(sig));

        assertThat(r.isValid()).as("verification error: %s", r.getError()).isTrue();
        assertThat(r.getPersonalNumber()).isEqualTo(BankIdFixture.TEST_PERSONAL_NUMBER);
        assertThat(r.getUsrVisibleData()).isEqualTo("Jag godkanner avtalet");
    }

    @Test
    @DisplayName("Revoked certificate is rejected")
    void revokedIsRejected() throws Exception {
        String sig = fx.signedResponseBase64("Jag godkanner avtalet");
        BankIdService.BankIdResult r = service.verify(sig, fx.ocspRevoked(sig));

        assertThat(r.isValid()).isFalse();
        assertThat(r.getError()).contains("status is not good");
    }

    @Test
    @DisplayName("OCSP response signed with the wrong key is rejected")
    void forgedOcspSignatureIsRejected() throws Exception {
        String sig = fx.signedResponseBase64("Jag godkanner avtalet");
        BankIdService.BankIdResult r = service.verify(sig, fx.ocspWrongSignature(sig));

        assertThat(r.isValid()).isFalse();
        assertThat(r.getError()).contains("signature is not valid");
    }

    @Test
    @DisplayName("OCSP responder from another CA is rejected")
    void foreignResponderIsRejected() throws Exception {
        String sig = fx.signedResponseBase64("Jag godkanner avtalet");
        BankIdService.BankIdResult r = service.verify(sig, fx.ocspForeignIssuer(sig));

        assertThat(r.isValid()).isFalse();
        assertThat(r.getError()).contains("same CA");
    }

    @Test
    @DisplayName("OCSP response belonging to a different signature is rejected")
    void replayedOcspIsRejected() throws Exception {
        String sigA = fx.signedResponseBase64("Avtal A");
        String sigB = fx.signedResponseBase64("Avtal B");
        // A response legitimately issued for signature A, presented with B.
        BankIdService.BankIdResult r = service.verify(sigB, fx.ocspResponseBase64(sigA));

        assertThat(r.isValid()).isFalse();
        assertThat(r.getError()).contains("nonce");
    }

    @Test
    @DisplayName("OCSP response without a nonce is rejected")
    void missingNonceIsRejected() throws Exception {
        String sig = fx.signedResponseBase64("Jag godkanner avtalet");
        BankIdService.BankIdResult r = service.verify(sig, fx.ocspWithoutNonce(sig));

        assertThat(r.isValid()).isFalse();
        assertThat(r.getError()).contains("no nonce");
    }

    @Test
    @DisplayName("OCSP response with a self-issued responder carrying the CA's DN is rejected")
    void selfIssuedResponderWithCopiedIssuerDnIsRejected() throws Exception {
        String sig = fx.signedResponseBase64("Jag godkanner avtalet");
        BankIdService.BankIdResult r = service.verify(sig, fx.ocspSelfIssuedResponder(sig));

        // The issuer DN matches the bank CA's, so the string comparison alone
        // would let this through. Only verification under the issuing CA's
        // public key rejects it.
        assertThat(r.isValid()).isFalse();
        assertThat(r.getError()).contains("OCSP_RESPONDER_NOT_ISSUED_BY_CA");
    }

    @Test
    @DisplayName("OCSP responder without EKU id-kp-OCSPSigning is rejected")
    void responderWithoutOcspSigningEkuIsRejected() throws Exception {
        String sig = fx.signedResponseBase64("Jag godkanner avtalet");
        BankIdService.BankIdResult r = service.verify(sig, fx.ocspResponderWithoutEku(sig));

        assertThat(r.isValid()).isFalse();
        assertThat(r.getError()).contains("OCSP_RESPONDER_EKU_MISSING");
    }

    @Test
    @DisplayName("A missing OCSP response is a rejection, not a downgrade")
    void missingOcspResponseIsRejected() throws Exception {
        String sig = fx.signedResponseBase64("Jag godkanner avtalet");
        BankIdService.BankIdResult r = service.verify(sig, null);

        assertThat(r.isValid()).isFalse();
        assertThat(r.getError()).contains("BANKID_OCSP_REQUIRED");
    }

    @Test
    @DisplayName("usrNonVisibleData carrying the canonical binding matches the expected string")
    void canonicalBindingIsCarriedInSignedPayload() throws Exception {
        byte[] csrDer = "pretend-this-is-a-csr".getBytes(java.nio.charset.StandardCharsets.UTF_8);
        String binding = BankIdService.expectedBinding("5569743098", "1231015932", csrDer);
        String sig = fx.signedResponseBoundTo("Jag godkanner avtalet", binding);

        BankIdService.BankIdResult r = service.verify(sig, fx.ocspResponseBase64(sig));

        assertThat(r.isValid()).as("verification error: %s", r.getError()).isTrue();
        assertThat(r.getUsrNonVisibleData()).isEqualTo(binding);
        assertThat(BankIdService.isBoundToRequest(r.getUsrNonVisibleData(), binding)).isTrue();
    }

    @Test
    @DisplayName("A signature bound to a different CSR does not satisfy the binding")
    void bindingForAnotherCsrIsRejected() throws Exception {
        byte[] csrA = "csr-A".getBytes(java.nio.charset.StandardCharsets.UTF_8);
        byte[] csrB = "csr-B".getBytes(java.nio.charset.StandardCharsets.UTF_8);
        String bindingA = BankIdService.expectedBinding("5569743098", "1231015932", csrA);
        String bindingB = BankIdService.expectedBinding("5569743098", "1231015932", csrB);

        // A genuine, valid BankID signature — collected for request A.
        String sig = fx.signedResponseBoundTo("Jag godkanner avtalet", bindingA);
        BankIdService.BankIdResult r = service.verify(sig, fx.ocspResponseBase64(sig));

        assertThat(r.isValid()).as("the signature itself is genuine").isTrue();
        assertThat(BankIdService.isBoundToRequest(r.getUsrNonVisibleData(), bindingB))
                .as("replaying it against request B must not satisfy the binding")
                .isFalse();
    }

    @Test
    @DisplayName("Missing usrNonVisibleData never satisfies the binding")
    void absentBindingIsRejected() {
        String binding = BankIdService.expectedBinding("5569743098", "1231015932", new byte[] { 1 });

        assertThat(BankIdService.isBoundToRequest(null, binding)).isFalse();
        assertThat(BankIdService.isBoundToRequest("   ", binding)).isFalse();
    }

    @Test
    @DisplayName("Payload injected outside the signed element is not returned")
    void injectedPayloadOutsideSignedDataIsIgnored() throws Exception {
        String sig = fx.signedResponseBase64("Jag godkanner avtalet", true, false);
        BankIdService.BankIdResult r = service.verify(sig, fx.ocspResponseBase64(sig));

        // The signature still validates — the injected element is not covered
        // by it. What must not happen is that the caller is told the injected
        // text is what was signed.
        assertThat(r.getUsrVisibleData()).isEqualTo("Jag godkanner avtalet");
        assertThat(r.getUsrVisibleData()).doesNotContain("INJICERAD");
    }

    @Test
    @DisplayName("Two bankIdSignedData elements are rejected as ambiguous")
    void duplicateSignedDataIsRejected() throws Exception {
        String sig = fx.signedResponseBase64("Jag godkanner avtalet", false, true);
        BankIdService.BankIdResult r = service.verify(sig, fx.ocspResponseBase64(sig));

        assertThat(r.isValid()).isFalse();
    }

    @Test
    @DisplayName("A chain not rooted at a pinned anchor is rejected")
    void chainNotRootedAtPinnedAnchorIsRejected() throws Exception {
        String sig = fx.signedResponseBase64("Jag godkanner avtalet");
        // Same signature, but the service pins an unrelated root.
        BankIdService other = new BankIdService(
                java.util.Set.of(new java.security.cert.TrustAnchor(fx.foreignCaCert, null)));
        BankIdService.BankIdResult r = other.verify(sig, fx.ocspResponseBase64(sig));

        assertThat(r.isValid()).isFalse();
    }
}
