package eu.gillstrom.hsm.service;

import eu.gillstrom.hsm.testsupport.BankIdFixture;
import java.util.Date;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Exercises the verification steps that had no test coverage: OCSP status,
 * OCSP response signature, responder issuer, nonce binding, and the scoping of
 * payload reads to the element the signature actually covers.
 *
 * <p>Extended in v1.4.0 with the responder-authority checks (a self-issued
 * responder certificate carrying a copied issuer DN; a responder without EKU
 * {@code id-kp-OCSPSigning}), the now-mandatory OCSP response, and the canonical
 * request binding carried in {@code usrNonVisibleData}.</p>
 *
 * <p>All material is generated by {@link BankIdFixture}. Nothing here is a
 * recorded production signature.</p>
 */
class BankIdSignatureVerificationTest {

    private BankIdFixture fx;
    private BankIdService service;

    @BeforeEach
    void setUp() throws Exception {
        fx = new BankIdFixture();
        service = new BankIdService(fx.anchors());
    }

    @Test
    @DisplayName("Valid signature, chain and OCSP response are accepted")
    void happyPath() throws Exception {
        String sig = fx.signedResponseBase64("Jag godkanner avtalet");
        BankIdService.BankIdResult r = service.verify(sig, fx.ocspResponseBase64(sig));

        assertThat(r.isValid()).as("verification error: %s", r.getError()).isTrue();
        assertThat(r.getPersonalNumber()).isEqualTo(BankIdFixture.TEST_PERSONAL_NUMBER);
        assertThat(r.getUsrVisibleData()).isEqualTo("Jag godkanner avtalet");
    }

    @Test
    @DisplayName("Revoked certificate is rejected")
    void revokedIsRejected() throws Exception {
        String sig = fx.signedResponseBase64("Jag godkanner avtalet");
        BankIdService.BankIdResult r = service.verify(sig, fx.ocspRevoked(sig));

        assertThat(r.isValid()).isFalse();
        assertThat(r.getError()).contains("status is not good");
    }

    @Test
    @DisplayName("OCSP response signed with the wrong key is rejected")
    void forgedOcspSignatureIsRejected() throws Exception {
        String sig = fx.signedResponseBase64("Jag godkanner avtalet");
        BankIdService.BankIdResult r = service.verify(sig, fx.ocspWrongSignature(sig));

        assertThat(r.isValid()).isFalse();
        assertThat(r.getError()).contains("signature is not valid");
    }

    @Test
    @DisplayName("OCSP responder from another CA is rejected")
    void foreignResponderIsRejected() throws Exception {
        String sig = fx.signedResponseBase64("Jag godkanner avtalet");
        BankIdService.BankIdResult r = service.verify(sig, fx.ocspForeignIssuer(sig));

        assertThat(r.isValid()).isFalse();
        assertThat(r.getError()).contains("same CA");
    }

    @Test
    @DisplayName("OCSP response belonging to a different signature is rejected")
    void replayedOcspIsRejected() throws Exception {
        String sigA = fx.signedResponseBase64("Avtal A");
        String sigB = fx.signedResponseBase64("Avtal B");
        // A response legitimately issued for signature A, presented with B.
        BankIdService.BankIdResult r = service.verify(sigB, fx.ocspResponseBase64(sigA));

        assertThat(r.isValid()).isFalse();
        assertThat(r.getError()).contains("nonce");
    }

    @Test
    @DisplayName("OCSP response without a nonce is rejected")
    void missingNonceIsRejected() throws Exception {
        String sig = fx.signedResponseBase64("Jag godkanner avtalet");
        BankIdService.BankIdResult r = service.verify(sig, fx.ocspWithoutNonce(sig));

        assertThat(r.isValid()).isFalse();
        assertThat(r.getError()).contains("no nonce");
    }

    @Test
    @DisplayName("OCSP response with a self-issued responder carrying the CA's DN is rejected")
    void selfIssuedResponderWithCopiedIssuerDnIsRejected() throws Exception {
        String sig = fx.signedResponseBase64("Jag godkanner avtalet");
        BankIdService.BankIdResult r = service.verify(sig, fx.ocspSelfIssuedResponder(sig));

        // The issuer DN matches the bank CA's, so the string comparison alone
        // would let this through. Only verification under the issuing CA's
        // public key rejects it.
        assertThat(r.isValid()).isFalse();
        assertThat(r.getError()).contains("OCSP_RESPONDER_NOT_ISSUED_BY_CA");
    }

    @Test
    @DisplayName("OCSP responder without EKU id-kp-OCSPSigning is rejected")
    void responderWithoutOcspSigningEkuIsRejected() throws Exception {
        String sig = fx.signedResponseBase64("Jag godkanner avtalet");
        BankIdService.BankIdResult r = service.verify(sig, fx.ocspResponderWithoutEku(sig));

        assertThat(r.isValid()).isFalse();
        assertThat(r.getError()).contains("OCSP_RESPONDER_EKU_MISSING");
    }

    @Test
    @DisplayName("A missing OCSP response is a rejection, not a downgrade")
    void missingOcspResponseIsRejected() throws Exception {
        String sig = fx.signedResponseBase64("Jag godkanner avtalet");
        BankIdService.BankIdResult r = service.verify(sig, null);

        assertThat(r.isValid()).isFalse();
        assertThat(r.getError()).contains("BANKID_OCSP_REQUIRED");
    }

    @Test
    @DisplayName("usrNonVisibleData carrying the canonical binding matches the expected string")
    void canonicalBindingIsCarriedInSignedPayload() throws Exception {
        byte[] csrDer = "pretend-this-is-a-csr".getBytes(java.nio.charset.StandardCharsets.UTF_8);
        String binding = BankIdService.expectedBinding("5569743098", "1231015932", eu.gillstrom.hsm.model.VerificationResponse.CertificateType.SIGNING, csrDer);
        String sig = fx.signedResponseBoundTo("Jag godkanner avtalet", binding);

        BankIdService.BankIdResult r = service.verify(sig, fx.ocspResponseBase64(sig));

        assertThat(r.isValid()).as("verification error: %s", r.getError()).isTrue();
        assertThat(r.getUsrNonVisibleData()).isEqualTo(binding);
        assertThat(BankIdService.isBoundToRequest(r.getUsrNonVisibleData(), binding)).isTrue();
    }

    @Test
    @DisplayName("A signature bound to a different CSR does not satisfy the binding")
    void bindingForAnotherCsrIsRejected() throws Exception {
        byte[] csrA = "csr-A".getBytes(java.nio.charset.StandardCharsets.UTF_8);
        byte[] csrB = "csr-B".getBytes(java.nio.charset.StandardCharsets.UTF_8);
        String bindingA = BankIdService.expectedBinding("5569743098", "1231015932", eu.gillstrom.hsm.model.VerificationResponse.CertificateType.SIGNING, csrA);
        String bindingB = BankIdService.expectedBinding("5569743098", "1231015932", eu.gillstrom.hsm.model.VerificationResponse.CertificateType.SIGNING, csrB);

        // A genuine, valid BankID signature — collected for request A.
        String sig = fx.signedResponseBoundTo("Jag godkanner avtalet", bindingA);
        BankIdService.BankIdResult r = service.verify(sig, fx.ocspResponseBase64(sig));

        assertThat(r.isValid()).as("the signature itself is genuine").isTrue();
        assertThat(BankIdService.isBoundToRequest(r.getUsrNonVisibleData(), bindingB))
                .as("replaying it against request B must not satisfy the binding")
                .isFalse();
    }

    @Test
    @DisplayName("Missing usrNonVisibleData never satisfies the binding")
    void absentBindingIsRejected() {
        String binding = BankIdService.expectedBinding("5569743098", "1231015932", eu.gillstrom.hsm.model.VerificationResponse.CertificateType.SIGNING, new byte[] { 1 });

        assertThat(BankIdService.isBoundToRequest(null, binding)).isFalse();
        assertThat(BankIdService.isBoundToRequest("   ", binding)).isFalse();
    }

    @Test
    @DisplayName("Payload injected outside the signed element is not returned")
    void injectedPayloadOutsideSignedDataIsIgnored() throws Exception {
        String sig = fx.signedResponseBase64("Jag godkanner avtalet", true, false);
        BankIdService.BankIdResult r = service.verify(sig, fx.ocspResponseBase64(sig));

        // The signature still validates — the injected element is not covered
        // by it. What must not happen is that the caller is told the injected
        // text is what was signed.
        assertThat(r.getUsrVisibleData()).isEqualTo("Jag godkanner avtalet");
        assertThat(r.getUsrVisibleData()).doesNotContain("INJICERAD");
    }

    @Test
    @DisplayName("Two bankIdSignedData elements are rejected as ambiguous")
    void duplicateSignedDataIsRejected() throws Exception {
        String sig = fx.signedResponseBase64("Jag godkanner avtalet", false, true);
        BankIdService.BankIdResult r = service.verify(sig, fx.ocspResponseBase64(sig));

        assertThat(r.isValid()).isFalse();
    }

    @Test
    @DisplayName("A chain not rooted at a pinned anchor is rejected")
    void chainNotRootedAtPinnedAnchorIsRejected() throws Exception {
        String sig = fx.signedResponseBase64("Jag godkanner avtalet");
        // Same signature, but the service pins an unrelated root.
        BankIdService other = new BankIdService(
                java.util.Set.of(new java.security.cert.TrustAnchor(fx.foreignCaCert, null)));
        BankIdService.BankIdResult r = other.verify(sig, fx.ocspResponseBase64(sig));

        assertThat(r.isValid()).isFalse();
    }

    @Test
    @DisplayName("A signature chaining to the test root is rejected unless the test root is allowed")
    void testRootIsNotTrustedByDefault() throws Exception {
        String sig = fx.signedResponseBase64("Jag godkanner avtalet");
        BankIdService production = new BankIdService(
                BankIdService.trustAnchors(fx.foreignCaCert, fx.rootCert, false));

        BankIdService.BankIdResult r = production.verify(sig, fx.ocspResponseBase64(sig));

        assertThat(r.isValid()).isFalse();
    }

    @Test
    @DisplayName("A signature chaining to the test root is accepted when the test root is allowed")
    void testRootIsTrustedWhenAllowed() throws Exception {
        String sig = fx.signedResponseBase64("Jag godkanner avtalet");
        BankIdService dev = new BankIdService(
                BankIdService.trustAnchors(fx.foreignCaCert, fx.rootCert, true));

        BankIdService.BankIdResult r = dev.verify(sig, fx.ocspResponseBase64(sig));

        assertThat(r.isValid()).as("verification error: %s", r.getError()).isTrue();
    }

    @Test
    @DisplayName("The pinned Test BankID root is an anchor only when allow-test-root is set")
    void pinnedTestRootIsAnAnchorOnlyWhenAllowed() {
        assertThat(BankIdService.pinnedTrustAnchors(false))
                .hasSize(1)
                .noneMatch(a -> a.getTrustedCert().getSubjectX500Principal().getName()
                        .contains("Test BankID Root CA v1 Test"));
        assertThat(BankIdService.pinnedTrustAnchors(true))
                .hasSize(2)
                .anyMatch(a -> a.getTrustedCert().getSubjectX500Principal().getName()
                        .contains("Test BankID Root CA v1 Test"));
    }

    // ------------------------------------------------------------------
    // Freshness, issuer match and single use
    // ------------------------------------------------------------------

    @Test
    @DisplayName("An OCSP response older than the maximum signature age is rejected")
    void staleProducedAtIsRejected() throws Exception {
        String sig = fx.signedResponseBase64("Jag godkanner avtalet");
        Date sixteenMinutesAgo = new Date(System.currentTimeMillis() - 16 * 60_000L);
        BankIdService.BankIdResult r = service.verify(sig, fx.ocspProducedAt(sig, sixteenMinutesAgo));

        assertThat(r.isValid()).isFalse();
        assertThat(r.getError()).contains("BANKID_SIGNATURE_TOO_OLD");

        Date fourteenMinutesAgo = new Date(System.currentTimeMillis() - 14 * 60_000L);
        assertThat(service.verify(sig, fx.ocspProducedAt(sig, fourteenMinutesAgo)).isValid()).isTrue();
    }

    @Test
    @DisplayName("The maximum signature age is configurable")
    void maximumAgeIsConfigurable() throws Exception {
        BankIdService strict = new BankIdService(fx.anchors(), java.time.Clock.systemUTC(),
                java.time.Duration.ofMinutes(1));
        String sig = fx.signedResponseBase64("Jag godkanner avtalet");
        Date twoMinutesAgo = new Date(System.currentTimeMillis() - 2 * 60_000L);
        assertThat(strict.verify(sig, fx.ocspProducedAt(sig, twoMinutesAgo)).getError())
                .contains("BANKID_SIGNATURE_TOO_OLD");
    }

    @Test
    @DisplayName("A non-positive maximum age is refused at construction")
    void nonPositiveMaximumAgeIsRefused() {
        org.assertj.core.api.Assertions.assertThatThrownBy(() -> new BankIdService(fx.anchors(),
                java.time.Clock.systemUTC(), java.time.Duration.ZERO)).isInstanceOf(IllegalArgumentException.class);
        org.assertj.core.api.Assertions.assertThatThrownBy(() -> new BankIdService(fx.anchors(),
                java.time.Clock.systemUTC(), java.time.Duration.ofMinutes(-1))).isInstanceOf(IllegalArgumentException.class);
    }

    @Test
    @DisplayName("An OCSP response from the future, beyond the clock skew, is rejected")
    void futureProducedAtOrThisUpdateIsRejected() throws Exception {
        String sig = fx.signedResponseBase64("Jag godkanner avtalet");
        Date sixMinutesAhead = new Date(System.currentTimeMillis() + 6 * 60_000L);
        assertThat(service.verify(sig, fx.ocspProducedAt(sig, sixMinutesAhead)).getError())
                .contains("producedAt is in the future");
        assertThat(service.verify(sig, fx.ocspThisUpdate(sig, sixMinutesAhead)).getError())
                .contains("thisUpdate is in the future");

        Date fourMinutesAhead = new Date(System.currentTimeMillis() + 4 * 60_000L);
        assertThat(service.verify(sig, fx.ocspProducedAt(sig, fourMinutesAhead)).isValid()).isTrue();
        assertThat(service.verify(sig, fx.ocspThisUpdate(sig, fourMinutesAhead)).isValid()).isTrue();
    }

    @Test
    @DisplayName("An OCSP entry for the same serial under another issuer is not this certificate's")
    void sameSerialOtherIssuerIsRejected() throws Exception {
        String sig = fx.signedResponseBase64("Jag godkanner avtalet");
        BankIdService.BankIdResult r = service.verify(sig, fx.ocspSameSerialOtherIssuer(sig));

        assertThat(r.isValid()).isFalse();
        assertThat(r.getError()).contains("no entry for certificate serial");
    }

    @Test
    @DisplayName("A BankID signature can be consumed once")
    void aSignatureIsConsumedOnce() throws Exception {
        String sig = fx.signedResponseBase64("Jag godkanner avtalet");
        BankIdService.BankIdResult r = service.verify(sig, fx.ocspResponseBase64(sig));

        assertThat(service.consume(sig, r.getSignatureTime())).isTrue();
        assertThat(service.consume(sig, r.getSignatureTime())).isFalse();
        String other = fx.signedResponseBase64("Annan text");
        assertThat(service.consume(other, r.getSignatureTime())).isTrue();
    }

    @Test
    @DisplayName("A consumed signature is forgotten once it is too old to verify anyway")
    void consumedSignaturesExpire() throws Exception {
        java.util.concurrent.atomic.AtomicReference<java.time.Instant> now =
                new java.util.concurrent.atomic.AtomicReference<>(java.time.Instant.now());
        java.time.Clock clock = new java.time.Clock() {
            public java.time.ZoneId getZone() { return java.time.ZoneOffset.UTC; }
            public java.time.Clock withZone(java.time.ZoneId zone) { return this; }
            public java.time.Instant instant() { return now.get(); }
        };
        BankIdService timed = new BankIdService(fx.anchors(), clock, java.time.Duration.ofMinutes(15));
        java.time.Instant producedAt = now.get();
        assertThat(timed.consume("sig-a", producedAt)).isTrue();
        assertThat(timed.usedSignatureCount()).isEqualTo(1);

        now.set(producedAt.plus(java.time.Duration.ofMinutes(19)));
        assertThat(timed.consume("sig-a", producedAt)).as("still within age plus skew").isFalse();

        now.set(producedAt.plus(java.time.Duration.ofMinutes(20)).plusSeconds(1));
        assertThat(timed.consume("sig-b", now.get())).isTrue();
        assertThat(timed.usedSignatureCount()).as("sig-a is past its window and dropped").isEqualTo(1);
        assertThat(timed.consume("sig-b", now.get())).isFalse();
    }
}
